stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/technopark.csv
      - data/raw/thampanoor.csv
      - params.yaml
    outs:
      - data/processed/
      - models/scaler.pkl
    params:
      - window_size
      - horizon
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/
      - params.yaml
    outs:
      - models/technopark_model.keras
      - models/thampanoor_model.keras
    metrics:
      - metrics.json:
          cache: false
    plots:
      - version.json:
          cache: false